export const TRAITS_DRAENAK = [
	{
		id: "trait-1",
		name: "Afinidade Arcana",
		description: "Conexão natural com forças arcanas, podendo fazer uso de Competências mágicas utilizando Vontade e sem necessidade de auxílio arcano",
		cost: 20,
		level: 0,
	},
	{
		id: "trait-2",
		name: "Arcanismo Gestual",
		description: "Através de estudo, torna-se capaz de executar ações arcanas utilizando seu conhecimento. Acessa Competências mágicas, porém com Intelecto e muda Vínculo inicial para 10",
		cost: 15,
		level: 0,
	},
	{
		id: "trait-3",
		name: "Surdez Arcana",
		description: "Falta de capacidade total em acessar energias arcanas",
		cost: -20,
		level: 0,
	},
	{
		id: "trait-4",
		name: "Maldição",
		description: "Escolha uma maldição simples com quem estiver narrando a aventura.",
		cost: -5,
		level: 0,
	},
	{
		id: "trait-5",
		name: "Conexão Etérea",
		description: "Torna-se capaz de utilizar Competências Arcanas utilizando a própria Vontade. Contudo, por necessitar manter uma boa conexão com entidades ou forças elementais etéreas que nutrem esse poder arcano, o Vínculo inicial é 5",
		cost: 10,
		level: 0,
	},
	{
		id: "trait-6",
		name: "Ambidestria",
		description: "Capacidade de (as vezes) não derrubar as coisas com as duas mãos",
		cost: 5,
		level: 0,
	},
  {
		id: "trait-7",
		name: "Impulsivo",
		description: "É mais fácil de ser provocado. Situações que tentar resistir a impulsoss ou provocações são testadas com Desvantagem",
		cost: -5,
		level: 0,
	},
  {
		id: "trait-8",
		name: "Chamado do Dever",
		description: "Alguém muito apegado aos deveres e seguir ordens que segue. Uma personagem assim as vezes considera que vale tudo para que o objetivo final, ou uma ordem, seja alcançada.",
		cost: -10,
		level: 0,
	},
  {
		id: "trait-9",
		name: "Voto",
		description: "Você fez alguma promessa ou voto que, se quebrado, precisa de ações de reparação.",
		cost: -5,
		level: 0,
	},
];
